alma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url('^reset/', views.resetView),
    url(r'^course/', include('course.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^livereload/', include('livereload.urls')),
    url(r'^', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^$', views.ForumView.as_view(), name='index'),
    # url(r'^test/', views.IndexView.as_view(), name='detail'),
    url(r'^new/', views.NewPostView.as_view(), name='new'),
    url(r'^(?P<post_id>[0-9]+)/', views.PostView.as_view(), name='detail'),
]

forum/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError, ObjectDoesNotExist

from taggit.managers import TaggableManager

from course.models import Course

# TODO
# https://github.com/alex/django-taggit
# https://github.com/shanbay/django-vote

def attachment_path(post, filename):
    return 'post_{0}/{1}'.format(post.id, filename)

class Post(models.Model):
    FORUM = 1
    COMMENT = 2
    ASSIGNMENT = 3
    SUBMISSION = 4
    TYPE_CHOICES = (
            (FORUM, 'Forum Post'),
            (FORUM, 'Comment'),
            (ASSIGNMENT, 'Assignment'),
            (SUBMISSION, 'Assignment Submission')
    )

    title = models.CharField(max_length=64)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    anonymous = models.BooleanField(default=False)
    pinned = models.BooleanField(default=False)
    content = models.TextField(blank=True)
    tags = TaggableManager(blank=True)
    pub_time = models.DateTimeField(auto_now_add=True)
    edit_time = models.DateTimeField(auto_now=True)


    attachment = models.FileField(blank=True, null=True, upload_to=attachment_path);
    type = models.IntegerField(choices=TYPE_CHOICES, default=FORUM)
    due_date = models.DateTimeField(null=True)
    grade = models.IntegerField(blank=True, null=True)


    def clean_fields(self, exclude=None):
        super(Post, self).clean_fields(exclude=exclude)
        if self.parent == self:
            raise ValidationError({'parent': 'Parent cannot be self.'})

    def author_name(self):
        if self.anonymous:
            return "Anonymous"
        else:
            return self.user.get_full_name()

    def get_grade_string(self, user_id):
        try:
            lastGraded = self.post_set.filter(user_id=user_id, grade__isnull=False).latest(field_name='pub_time')
            return lastGraded.grade
        except ObjectDoesNotExist:
            return '-'

    def __str__(self):
        return self.title

forum/forms.py
from django import forms

from .models import Post

import bleach

import pprint
# pprint.PrettyPrinter().pprint(vars(self))

class RTFInput(forms.widgets.Input):
    input_type = 'text'
    template_name = 'forum/summernote_widget.html'

    def __init__(self, attrs={'class':'summernote'}, **kwargs):
        if attrs['class'] != 'summernote':
            if attrs['class'] is None:
                attrs['class'] = 'summernote'
            else:
                attrs['class'] += ' summernote'
        super().__init__(attrs, **kwargs)

class RTFField(forms.CharField):
    widget = RTFInput

    def __init__(self, *args, **kwargs):
        if kwargs['widget'] == forms.Textarea:
            # ModelForm > TextField passes in widget=forms.Textarea
            kwargs['widget'] = RTFInput
        super().__init__(*args, **kwargs)


    def clean(self, value):
        return bleach.clean(super().clean(value),
                tags = ['div', 'p', 'b', 'u', 'i', 'br', 'sup', 'strike', 'sub', 'img', 'ol', 'ul', 'li', 'table', 'thead', 'tbody', 'tr', 'td', 'th', 'a', 'span'],
                attributes = {
                    '*': 'style',
                    'span':'class',
                    'a':'href',
                    'img':['src','alt','width','height'],
                    },
                styles = ['font-size', 'background-color', 'color', 'width', 'height', 'text-align', 'margin-left', 'margin-right'],
                protocols = bleach.ALLOWED_PROTOCOLS + ['data'],
                )


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'anonymous', 'content', 'tags']
        field_classes = {
                'content': RTFField
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['content'].widget.attrs.update({'class' : 'materialize-textarea'})


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'anonymous']
        labels = {'content': "Add a reply"}
        field_classes = {
                'content': RTFField
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['content'].widget.attrs.update({'class' : 'materialize-textarea'})

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic import TemplateView, FormView
from django.urls import reverse
from django.contrib.auth import get_user
from django.http import Http404

from course.views import CourseView
from course.models import Course

from .models import Post
from .forms import NewPostForm, NewCommentForm

class ForumView(CourseView):
    template_name = 'forum/posts.html'

    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['post_list'] = context['course'].post_set.filter(parent__isnull=True, type=Post.FORUM).order_by('-pub_time')
        return context


class PostView(CourseView, FormView):
    # template_name = 'forum/detail_metro.html'
    template_name = 'forum/detail.html'
    form_class = NewCommentForm

    def get_context_data(self, post_id, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        post = get_object_or_404(Post, pk=post_id, type=Post.FORUM)
        context['post'] = post

        return context

    def form_valid(self, form):
        kwargs = self.kwargs # post does not pass in kwargs
        comment = form.save(commit=False)
        comment.user = get_user(self.request)
        comment.course_id = kwargs['course_id']
        comment.parent_id = kwargs['post_id']
        comment.title = "Reply to post " + str(comment.parent_id)
        comment.type = Post.COMMENT
        comment.save()
        self.success_url = reverse('forum:detail', args=(kwargs['course_id'], kwargs['post_id']))
        return super().form_valid(form)


class NewPostView(CourseView, FormView):
    template_name = 'forum/new_post.html'
    form_class = NewPostForm

    def get_form(self):
        if self.request.GET and self.request.GET['id']:
            post = get_object_or_404(Post, pk=self.request.GET['id'], type=Post.FORUM, user_id=self.request.user.id)
            return self.form_class(instance=post, **self.get_form_kwargs())
        else:
            return self.form_class(**self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        kwargs = self.kwargs # post -> form_invalid does not pass in kwargs
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        kwargs = self.kwargs # post does not pass in kwargs
        # save new post here
        post = form.save(commit=False)
        post.user = get_user(self.request)
        post.course_id = kwargs['course_id']
        post.type = Post.FORUM
        post.save()
        self.success_url = reverse('forum:detail', args=(kwargs['course_id'], post.id))
        return super().form_valid(form)

forum/templates/forum/comment.html
<div class="comment">
	<div class="content">
		<a class="author" href="">{{ comment.author_name }}</a>
		<div class="metadata"><span class="date">{{ comment.pub_time }}</span></div>
		<div class="text">{{ comment.content }}</div>
		<div class="actions"><a class="reply" href="">Reply</a></div>
	</div>
	{% comment %} Use |length instead of .count because the data needs to be fetched anyway {% endcomment %}
	{% if comment.post_set.all|length != 0 %}
	<div class="comments">
		{% for comment in comment.post_set.all %}
		{% include 'forum/comment.html' %}
		{% endfor %}
	</div>
	{% endif %}
</div>

forum/templates/forum/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block main %}
	{% if user == post.user %}
	<a href="{% url 'forum:new' course.id %}?id={{ post.id }}" id="edit-post" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">mode_edit</i></a>
	{% endif %}

	<div id="info-content">
		<h4>Post Detail</h4>
		<p>This page shows a post. You can only see this page if you are a member of the course.</p>
		<h5>Security</h5>
		<p>The post HTML is put through a whitelist using libhtml5 so it is secure against CSS attacks or malicious Javascript.</p>
		<h5>Editing</h5>
		<p>If you are the owner of this post, you will have a red edit button on the bottom right.</p>
		<h5>Comments</h5>
		<p>Comments are shown below the post. Clicking on the comment area expands the Anonymous option and the submit button. The server will only accept your comment if you are a student of this course.</p>
	</div>

	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">{{ post.title }}</span>
				<p>{{ post.content | safe }}</p>
			</div>
			<div class="divider"></div>
			<div class="card-content">
				<div class="row clear">
					{% for tag in post.tags.all %}
					<div class="chip">{{ tag }}</div>
					{% endfor %}
					<span class="right grey-text">{{ post.author_name }} posted {{ post.pub_time | naturaltime }}</span>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="card">
			<div class="card-stacked">

				{% for comment in post.post_set.all %}
				<div id="comment-{{ comment.id }}" class="card-content">
					<div class="row">
						<b class="grey-text text-darken-3">{{ comment.author_name }}</b>
						<span class="right grey-text">{{ comment.pub_time | naturaltime }}</span>
					</div>
					<p>{{ comment.content|safe }}</p>
				</div>
				<div class="divider"></div>
				{% endfor %}

				<div class="card-content">
					<form id="new-reply" method="post">
						{% csrf_token %}
						<div class="row clear">
							<h6 class="grey-text text-darken-3">Add a reply</h6>
							<div class="input-field col s12 clear" style="margin: 0;">
								<!--<textarea id="new-reply-area" class="materialize-textarea" name="" cols="30" rows="10"></textarea>-->
								{{ form.content }}
								<!--{{ form.content.label_tag }}-->
							</div>
						</div>
						<div class="row clear hide" style="margin-top: 8px;">
							<button class="btn waves-effect waves-light" type="submit" name="action">
								Submit <i class="material-icons right">send</i>
							</button>
							<label class="right" style="margin-top: 8px;">
								<input name="{{ form.anonymous.name }}" type="checkbox" class="filled-in" />
								<span>{{ form.anonymous.label }}</span>
							</label>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

<script>
{% block document_ready %}
//$('#{{ form.content.id_for_label }}').focus(function () {

$('.summernote').summernote({
	placeholder: 'Add a reply',
	tabsize: 2,
	height: 100,
	minHeight: 100,
	maxHeight: 500,
	toolbar: [
		['style', ['bold', 'italic', 'underline', 'clear']],
		['font', ['strikethrough', 'superscript', 'subscript']],
		['fontsize', ['fontsize']],
		['color', ['color']],
		['para', ['ul', 'ol', 'paragraph']],
		['insert', ['link', 'picture', 'equation', 'table']]
		]
});

$('.summernote').on('summernote.focus', function () {
	$('form#new-reply .hide').removeClass('hide');
});

{% endblock %}
</script>

forum/templates/forum/index.html
{% extends 'course/base.html' %}

{% block course_content %}

<div class="ui main text container content">
	<h1 class="ui header">{{ course.get_name }} Posts</h1>
	<div class="ui divided items">
		{% for post in post_list %}
		<div class="item">
			<div class="content">
				<a class="header" href="{% url 'forum:detail' course.id post.id %}">{{ post.title }}</a>
				<div class="meta right floated">
					<span class="time">{{ post.pub_time }}</span>
				</div>
				<div class="meta">
					<span class="author">{{ post.author_name }}</span>
				</div>
				<div class="extra">
					{% for tag in post.tags.all %}
					<a class="ui label">{{ tag }}</a>
					{% endfor %}
				</div>
			</div>
			<!--<div class="ui divider"></div>-->
		</div>
		{% empty %}
		There are no posts.
		{% endfor %}
	</div>
</div>

{% endblock %}

forum/templates/forum/new.html
{% extends 'course/base.html' %}

{% block course_content %}

<div class="ui main text container content">
	<h1 class="ui header">New Post</h1>

	<form action="{% url 'forum:new' course.id %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit">
	</form>

</div>

{% endblock %}

forum/templates/forum/new_post.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %} | New Post{% endblock %}

{% block main %}
	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">New Post</span>
				<p>{{ post.content | safe }}</p>
			</div>
			<div class="divider"></div>
			<form id="new-post-form" method="POST">
				{% csrf_token %}
				<div class="card-content">
					<div class="row clear">
						<div class="input-field col s12">
							{{ form.title }}
							{{ form.title.label_tag }}
							{{ form.title.errors }}
						</div>
					</div>
					<div class="row clear">
						<div class="col s12">
							{{ form.content.label_tag }}
							{{ form.content }}
							{{ form.content.errors }}
						</div>
					</div>
					<br>
					<div class="row clear">
						<label>
							{{ form.anonymous }}
							<span>{{ form.anonymous.label }}</span>
						</label>
					</div>
				</div>
				<div class="card-action">
					<div class="right-align"><button class="btn" type="submit">Post</button></div>
				</div>
			</form>
		</div>
	</div>

{% endblock %}

<script>
{% block document_ready %}
$('#{{ form.content.id_for_label }}').focus(function () {
	$('form#new-reply .hide').removeClass('hide');
});

$('.summernote').summernote({
	placeholder: 'Post content',
	tabsize: 2,
	height: 100,
	minHeight: 100,
	maxHeight: 500,
	toolbar: [
		['style', ['bold', 'italic', 'underline', 'clear']],
		['font', ['strikethrough', 'superscript', 'subscript']],
		['fontsize', ['fontsize']],
		['color', ['color']],
		['para', ['ul', 'ol', 'paragraph']],
		['insert', ['link', 'picture', 'equation', 'table']]
		]
});
{% endblock %}
</script>

forum/templates/forum/posts.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block style %}
.post-panel {
	position: relative;
}
.post-panel:hover {
	background-color: rgba(0, 0, 0, 0.05);
}

span.post-link {
	position: absolute;
	width: 100%;
	height: 100%;
	top: 0;
	left: 0;
	z-index: 1;
}
{% endblock %}	

{% block main %}
	<a href="{% url 'forum:new' course.id %}" id="edit-post" class="btn-floating btn-large waves-effect waves-light blue"><i class="material-icons">add</i></a>
	<div id="edit-tap-target" class="tap-target blue" data-target="edit-post">
		<div class="tap-target-content">
			<h5>Create a Post</h5>
			<p>Theres nothing here yet. Click the <i class="material-icons">add</i> to create a new post.</p>
		</div>
	</div>

	<div id="info-content">
		<h4>Forum Posts</h4>
		<p>This page shows the course forum. You can only see this page if you are a member of the course</p>
		<h5>New Post</h5>
		<p>Click the bottom right blue + to add a new post.</p>
	</div>

	<div class="row">
		<div class="card">
			<div class="card-content">
				<span class="card-title">{{ course.get_name }} Forum</span>
			</div>
			<div class="divider"></div>
			<div class="card-stacked">
				{% if post_list %}
				{% for post in post_list %}
				<div id="post-{{ post.id }}" class="card-content post-panel">
					<a href="{% url 'forum:detail' course.id post.id %}"><span class="post-link"></span></a>
					<div class="row">
						<a href="{% url 'forum:detail' course.id post.id %}"><b class="grey-text text-darken-3">{{ post.title }}</b></a>
						<span class="right grey-text">{{ post.pub_time | naturaltime }}</span>
					</div>
					<p>{{ post.content|safe|truncatechars_html:200 }}</p>
				</div>
				<div class="divider"></div>
				{% endfor %}
				{% else %}
				<div class="card-content">
					<p>There's nothing here. Click the <span class="blue-text">blue</span> Plus button on the bottom right to get started.</p>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

<script>
{% block document_ready %}
{% if not post_list %}
$('#edit-tap-target').featureDiscovery();
$('#edit-tap-target').featureDiscovery('open');
{% endif %}

{% endblock %}
</script>

forum/templates/forum/summernote_widget.html
<textarea name="{{ widget.name }}" {% include 'django/forms/widgets/attrs.html' %}>
{% if widget.value %}{{ widget.value }}{% endif %}
</textarea>