alma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url('^reset/', views.resetView),
    url(r'^course/', include('course.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^livereload/', include('livereload.urls')),
    url(r'^', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignments/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views

app_name = 'assignments'
urlpatterns = [
    url(r'^$', views.AssignmentListView.as_view(), name='index'),
    url(r'^new/', views.NewAssignmentView.as_view(), name='new'),
    url(r'^(?P<post_id>[0-9]+)/submition/(?P<pk>[0-9]+)', views.AssignmentSubmissionView.as_view(), name='submission'),
    url(r'^(?P<post_id>[0-9]+)/submit', views.AssignmentSubmitView.as_view(), name='submit'),
    url(r'^(?P<post_id>[0-9]+)/', views.AssignmentView.as_view(), name='detail'),
]

assignments/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils import timezone

from course.models import Course

class Assignment(models.Model):
    name = models.CharField(max_length=64)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    published = models.BooleanField(default=False)
    publish_time = models.DateTimeField(default=timezone.now)
    grades_published = models.BooleanField(default=False)
    due = models.DateTimeField()
    description = models.TextField()
    accept_late = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class AssignmentAttachment(models.Model):
    name = models.CharField(max_length=64)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    file = models.FileField() # TODO

    def __str__(self):
        return self.name


class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    file = models.FileField(blank=True, null=True) # TODO
    content = models.TextField(blank=True, null=True)
    comments = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    grade = models.IntegerField(blank=True, null=True)
    when = models.DateTimeField(auto_now_add=True)

    def clean(self):
        if (self.content and self.file) or \
           (not self.content and not self.file):
            raise ValidationError('Assignment submission must either be a text submission or a file.')
        if (not self.assignment.accept_late and self.assignment.due < timezone.now()):
            raise ValidationError('Assignment is pass due and does not accept late submissions.')

    def __str__(self):
        return self.assignment.course.get_name() + ': ' + self.assignment.name + ': ' + self.user.get_full_name()

forum/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError, ObjectDoesNotExist

from taggit.managers import TaggableManager

from course.models import Course

# TODO
# https://github.com/alex/django-taggit
# https://github.com/shanbay/django-vote

def attachment_path(post, filename):
    return 'post_{0}/{1}'.format(post.id, filename)

class Post(models.Model):
    FORUM = 1
    COMMENT = 2
    ASSIGNMENT = 3
    SUBMISSION = 4
    TYPE_CHOICES = (
            (FORUM, 'Forum Post'),
            (FORUM, 'Comment'),
            (ASSIGNMENT, 'Assignment'),
            (SUBMISSION, 'Assignment Submission')
    )

    title = models.CharField(max_length=64)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    anonymous = models.BooleanField(default=False)
    pinned = models.BooleanField(default=False)
    content = models.TextField(blank=True)
    tags = TaggableManager(blank=True)
    pub_time = models.DateTimeField(auto_now_add=True)
    edit_time = models.DateTimeField(auto_now=True)


    attachment = models.FileField(blank=True, null=True, upload_to=attachment_path);
    type = models.IntegerField(choices=TYPE_CHOICES, default=FORUM)
    due_date = models.DateTimeField(null=True)
    grade = models.IntegerField(blank=True, null=True)


    def clean_fields(self, exclude=None):
        super(Post, self).clean_fields(exclude=exclude)
        if self.parent == self:
            raise ValidationError({'parent': 'Parent cannot be self.'})

    def author_name(self):
        if self.anonymous:
            return "Anonymous"
        else:
            return self.user.get_full_name()

    def get_grade_string(self, user_id):
        try:
            lastGraded = self.post_set.filter(user_id=user_id, grade__isnull=False).latest(field_name='pub_time')
            return lastGraded.grade
        except ObjectDoesNotExist:
            return '-'

    def __str__(self):
        return self.title

assignments/forms.py
from django import forms

from forum.models import Post
from forum.forms import RTFField

import bleach

import pprint
# pprint.PrettyPrinter().pprint(vars(self))

class NewAssignmentForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'anonymous', 'content', 'attachment', 'due_date']
        field_classes = {
                'content': RTFField
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class NewSubmissionForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'attachment']
        field_classes = {
                'content': RTFField
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

assignments/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from course.views import CourseView
from course.models import Course, Membership
from django.views.generic import TemplateView, FormView, UpdateView
from django.http import Http404
from django.core.exceptions import PermissionDenied


from forum.models import Post
from .forms import NewAssignmentForm, NewSubmissionForm


class AssignmentListView(CourseView):
    template_name = 'assignments/assignment_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_prof = self.request.user.membership_set.filter(id=self.kwargs['course_id'], type__gte=Membership.TA).exists()

        context['is_prof'] = is_prof
        context['post_list'] = context['course'].post_set.filter(parent__isnull=True, type=Post.ASSIGNMENT).order_by('-pub_time')
        return context

class AssignmentView(CourseView):
    template_name = 'assignments/detail.html'

    def get_context_data(self, post_id, **kwargs):
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(Post, pk=post_id, type=Post.ASSIGNMENT)

        is_prof = self.request.user.membership_set.filter(id=self.kwargs['course_id'], type__gte=Membership.TA).exists()

        context['is_prof'] = is_prof
        context['post'] = post
        if is_prof:
            context['submissions'] = post.post_set.filter(type=Post.SUBMISSION);
        else:
            context['submissions'] = post.post_set.filter(user_id=self.request.user.id, type=Post.SUBMISSION);
        return context

class AssignmentSubmissionView(CourseView, UpdateView):
    template_name = 'assignments/submission_detail.html'
    model = Post
    fields = ['grade']
    object = None
    success_url = None

    def get_context_data(self, post_id, pk, **kwargs):
        context = super().get_context_data(**kwargs)
        assignment = get_object_or_404(Post, pk=post_id, type=Post.ASSIGNMENT)
        submission = get_object_or_404(Post, pk=pk, type=Post.SUBMISSION)
        is_prof = self.request.user.membership_set.filter(id=self.kwargs['course_id'], type__gte=Membership.TA).exists()

        self.object = submission

        context['is_prof'] = is_prof
        context['assignment'] = assignment
        context['post'] = submission
        return context

    def post(self, request, *args, **kwargs):
        is_prof = self.request.user.membership_set.filter(id=self.kwargs['course_id'], type__gte=Membership.TA).exists()
        if is_prof:
            return super().post(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse('assignments:detail', args=(self.kwargs['course_id'], self.kwargs['post_id']))



class NewAssignmentView(CourseView, FormView):
    template_name = 'assignments/new_assignment.html'
    form_class = NewAssignmentForm

    def get_form(self):
        if self.request.GET and self.request.GET['id']:
            post = get_object_or_404(Post, pk=self.request.GET['id'], type=Post.ASSIGNMENT)
            return self.form_class(instance=post, **self.get_form_kwargs())
        else:
            return self.form_class(**self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        kwargs = self.kwargs # post -> form_invalid does not pass in kwargs
        context = super().get_context_data(**kwargs)
        return context

    def test_func(self):
        return super().test_func() and self.request.user.membership_set.filter(id=self.kwargs['course_id'], type__gte=Membership.TA).exists()

    def form_valid(self, form):
        kwargs = self.kwargs # post does not pass in kwargs

        post = form.save(commit=False)
        post.user_id = self.request.user.id
        post.course_id = kwargs['course_id']
        post.type = Post.ASSIGNMENT

        post.save()

        self.success_url = reverse('assignments:detail', args=(kwargs['course_id'], post.id))
        # self.success_url = self.request.path
        return super().form_valid(form)

class AssignmentSubmitView(CourseView, FormView):
    template_name = 'assignments/new_submission.html'
    form_class = NewSubmissionForm

    def get_context_data(self, **kwargs):
        kwargs = self.kwargs # post -> form_invalid does not pass in kwargs
        context = super().get_context_data(**kwargs)
        return context

    # def test_func(self):
    #     return super().test_func() and self.request.user.membership_set.filter(id=self.kwargs['course_id'], type__gte=Membership.TA).exists()

    def form_valid(self, form):
        kwargs = self.kwargs # post does not pass in kwargs

        post = form.save(commit=False)
        post.user_id = self.request.user.id
        post.course_id = kwargs['course_id']
        post.parent_id = kwargs['post_id']
        post.type = Post.SUBMISSION
        post.title = "Submission for Assignment " + kwargs['post_id']

        post.save()

        self.success_url = reverse('assignments:detail', args=(kwargs['course_id'], kwargs['post_id']))
        return super().form_valid(form)

assignments/templates/assignments/assignment_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load basename %}
{% load grade %}

{% block main %}
	{% if is_prof %}
	<a id="edit-post" href="{% url 'assignments:new' course.id %}" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
	{% endif %}

	<div id="info-content">
		<h4>Assignment List</h4>
		<p>This page shows the assignments associated with this course. You can only see this page if you are a member of the course.</p>
		<h5>New Assignments</h5>
		<p>If you are a professor for this course, you will have a blue new button on the bottom right.</p>
		<h5>Grades</h5>
		<p>Next to your assignment, it will show your grade. This grade is from the most recent submission that already has a grade.</p>
	</div>

	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">{{ course.get_name }} Assignments</span>
				{% if post_list %}
				<table class="highlight">
					<thead>
						<tr>
							<th>Assignment</th>
							<th>Due Date</th>
							<th>Grade</th>
						</tr>
					</thead>
					<tbody>
						{% for post in post_list %}
						<tr class="link-row" data-href="{% url 'assignments:detail' course.id post.id %}" style="cursor: pointer">
							<td>{{ post.title }}</td>
							<td>{{ post.due_date }}</td>
							<td>{% grade post user.id %}</td>
						</tr>
						{% endfor %}	

					</tbody>
				</table>
				{% endif %}	
			</div>
			{% if not post_list %}
			<div class="divider"></div>
			<div class="card-content">
				{% if is_prof %}
				<p>There's nothing here. Click the <span class="blue-text">blue</span> Plus button on the bottom right to get started.</p>
				{% else %}
				<p>There's nothing here. Please log in as a Professor or TA to add an assignment.</p>
				{% endif %}
			</div>
			{% endif %}	
		</div>
	</div>

{% endblock %}

<script>
{% block document_ready %}
$('.link-row').click(function() {
	window.location = $(this).data("href");
});
{% endblock %}
</script>

assignments/templates/assignments/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load basename %}

{% block main %}
	{% if user == post.user %}
	<a id="edit-post" href="{% url 'assignments:new' course.id %}?id={{ post.id }}" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">mode_edit</i></a>
	{% endif %}

	<div id="info-content">
		<h4>Assignment Detail</h4>
		<p>This page shows an assignments. You can only see this page if you are a member of the course.</p>
		<h5>Edit</h5>
		<p>If you are a professor or TA for this course, you will have a red edit button on the bottom right.</p>
		<h5>Submissions</h5>
		<p>Below the assignment, it will show your the submissions. If you are a student, it will show your submissions. If you are a professor or TA, it will show all submissions. If you are a student, you can only view your own submissions, if you are a prof, you can view all submissions.</p>
	</div>

	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">{{ post.title }}</span>
				<p>{{ post.content | safe }}</p>
				{% if post.attachment %}
				<br>
				<span><a href="{{ post.attachment.url }}"><i class="material-icons left">insert_drive_file</i>{{ post.attachment|basename }}</a></span>
				{% endif %}
			</div>
			<div class="card-action">
				<span class="left grey-text text-darken-1" style="padding-top: 0.5rem;">Due {{ post.due_date }}</span>
				<div class="right-align"><a class="btn" href="{% url 'assignments:submit' course.id post.id %}">Add Sumbission</a></div>
			</div>
		</div>
	</div>

	{% if submissions %}
	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">Submissions</span>
				<table class="highlight">
					<thead>
						<tr>
							{% if is_prof %}<th>Student</th>{% endif %}	
							<th>Time Submitted</th>
							<th>Grade</th>
						</tr>
					</thead>
					<tbody>
						{% for sub in submissions %}
						<tr class="link-row" data-href="{% url 'assignments:submission' course.id post.id sub.id %}" style="cursor: pointer">
							{% if is_prof %}<td>{{ sub.author_name }}</td>{% endif %}	
							<td>{{ sub.pub_time }}</td>
							<td>{{ sub.grade }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	{% endif %}
{% endblock %}

<script>
{% block document_ready %}
$('.link-row').click(function() {
	window.location = $(this).data("href");
});
{% endblock %}
</script>

assignments/templates/assignments/new_assignment.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %} | New Post{% endblock %}

{% block main %}
	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">New Assignment</span>
				<p>{{ post.content | safe }}</p>
			</div>
			<div class="divider"></div>
			<form id="new-post-form" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="card-content">
					<div class="row">
						<div class="input-field col s12">
							{{ form.title }}
							{{ form.title.label_tag }}
							{{ form.title.errors }}
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							{{ form.due_date }}
							{{ form.due_date.label_tag }}
							{% if form.due_date.errors %}
							<span class="helper-text red-text" data-error="wrong" data-success="right">{{ form.due_date.errors.0 }}</span>
							{% endif %}
						</div>
					</div>
					<br>
					<div class="row clear">
						<div class="col s12">
							{{ form.content.label_tag }}
							{{ form.content }}
							{% if form.content.errors %}
							<span class="helper-text red-text" data-error="wrong" data-success="right">{{ form.content.errors.0 }}</span>
							{% endif %}
						</div>
					</div>
					<br>
					<div class="row clear">
						<div class="file-field input-field">
							<div class="btn">
								<span>{{ form.attachment.label }}</span>
								{{ form.attachment }}
							</div>
							<div class="file-path-wrapper">
								<input class="file-path validate" type="text">
							</div>
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="right-align"><button class="btn" type="submit">Post Assignment</button></div>
				</div>
			</form>
		</div>
	</div>

{% endblock %}

<script>
{% block document_ready %}
$('.summernote').summernote({
	placeholder: 'Post content',
	tabsize: 2,
	height: 100,
	minHeight: 100,
	maxHeight: 500,
	toolbar: [
		['style', ['bold', 'italic', 'underline', 'clear']],
		['font', ['strikethrough', 'superscript', 'subscript']],
		['fontsize', ['fontsize']],
		['color', ['color']],
		['para', ['ul', 'ol', 'paragraph']],
		['insert', ['link', 'picture', 'equation', 'table']]
		]
});

$('#{{ form.due_date.auto_id }}').datepicker({
	format:'yyyy-mm-dd'
});

{% endblock %}
</script>

assignments/templates/assignments/new_submission.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %} | New Post{% endblock %}

{% block main %}
	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">New Submission</span>
			</div>
			<div class="divider"></div>
			<form id="new-post-form" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="card-content">
					<div class="row clear">
						<div class="col s12">
							{{ form.content.label_tag }}
							{{ form.content }}
							{% if form.content.errors %}
							<span class="helper-text red-text" data-error="wrong" data-success="right">{{ form.content.errors.0 }}</span>
							{% endif %}
						</div>
					</div>
					<br>
					<div class="row clear">
						<div class="file-field input-field">
							<div class="btn">
								<span>{{ form.attachment.label }}</span>
								{{ form.attachment }}
							</div>
							<div class="file-path-wrapper">
								<input class="file-path validate" type="text">
							</div>
						</div>
						<p>{{ form.errors }}</p>
						{% for field in form.fields %}
						<p>{{ field.errors }}</p>
						{% endfor %}	
					</div>
				</div>
				<div class="card-action">
					<div class="right-align"><button class="btn" type="submit">Submit</button></div>
				</div>
			</form>
		</div>
	</div>

{% endblock %}

<script>
{% block document_ready %}
$('.summernote').summernote({
	placeholder: 'Post content',
	tabsize: 2,
	height: 100,
	minHeight: 100,
	maxHeight: 500,
	toolbar: [
		['style', ['bold', 'italic', 'underline', 'clear']],
		['font', ['strikethrough', 'superscript', 'subscript']],
		['fontsize', ['fontsize']],
		['color', ['color']],
		['para', ['ul', 'ol', 'paragraph']],
		['insert', ['link', 'picture', 'equation', 'table']]
		]
});

$('#{{ form.due_date.auto_id }}').datepicker({
	format:'yyyy-mm-dd'
});

{% endblock %}
</script>

assignments/templates/assignments/submission_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load basename %}

{% block main %}
	<div class="row">
		<div id="post" class="card clear-m">
			<div class="card-content">
				<span class="card-title">Submission for <a href="{% url 'assignments:detail' course.id assignment.id %}">{{ assignment.title }}</a></span>
				<b>{{ post.author_name }}</b>
			</div>
			<div class="divider"></div>
			<div class="card-content">
				<p>{{ post.content | safe }}</p>
				{% if post.attachment %}
				<br>
				<span><a href="{{ post.attachment.url }}"><i class="material-icons left">insert_drive_file</i>{{ post.attachment|basename }}</a></span>
				{% endif %}
			</div>
			{% if is_prof %}
			<div class="divider"></div>
			<form method="POST">
				<div class="card-content">
					{% csrf_token %}
					<div class="row clear">
						<div class="input-field col s12">
							<input type="number" name="{{ form.grade.name }}" id="{{ form.grade.auto_id }}" value="{{ post.grade }}">
							{{ form.grade.label_tag }}
							{{ form.grade.label_tag }}
							{% if form.grade.errors %}
							<span class="helper-text red-text" data-error="wrong" data-success="right">{{ form.grade.errors.0 }}</span>
							{% endif %}
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="right-align"><button class="btn" type="submit">Submit Grade</button></div>
				</div>
			</form>
			{% else %}
			<div class="divider"></div>
			<div class="card-content">
				{% csrf_token %}
				<div class="row clear">
					<div class="col s12">
						{% if post.grade %}
						<p>Grade: {{ post.grade }}</p>
						{% else %}	
						<p>This submission has not yet been graded.</p>
						{% endif %}
					</div>
				</div>
			</div>
			{% endif %}
		</div>
	</div>
{% endblock %}

<script>
{% block document_ready %}
$('.link-row').click(function() {
	window.location = $(this).data("href");
});
{% endblock %}
</script>