alma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url('^reset/', views.resetView),
    url(r'^course/', include('course.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^livereload/', include('livereload.urls')),
    url(r'^', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignments/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views

app_name = 'assignments'
urlpatterns = [
    url(r'^$', views.AssignmentListView.as_view(), name='index'),
    url(r'^new/', views.NewAssignmentView.as_view(), name='new'),
    url(r'^(?P<post_id>[0-9]+)/submition/(?P<pk>[0-9]+)', views.AssignmentSubmissionView.as_view(), name='submission'),
    url(r'^(?P<post_id>[0-9]+)/submit', views.AssignmentSubmitView.as_view(), name='submit'),
    url(r'^(?P<post_id>[0-9]+)/', views.AssignmentView.as_view(), name='detail'),
]

forum/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^$', views.ForumView.as_view(), name='index'),
    # url(r'^test/', views.IndexView.as_view(), name='detail'),
    url(r'^new/', views.NewPostView.as_view(), name='new'),
    url(r'^(?P<post_id>[0-9]+)/', views.PostView.as_view(), name='detail'),
]

course/models.py
from django.db import models
from django.conf import settings

from alma.models import School

class Course(models.Model):
    department = models.CharField(max_length=4)
    number = models.IntegerField()
    title = models.CharField(max_length=64)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    pin = models.CharField(max_length=16, blank=True, null=True)

    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Membership')

    def __str__(self):
        return self.department + ' ' + str(self.number) + ': ' + self.title;

    def get_name(self):
        return self.department + ' ' + str(self.number)

class Membership(models.Model):
    STUDENT = 1
    TA = 2
    PROFESSOR = 3
    TYPE_CHOICES = (
            (STUDENT, 'Student'),
            (TA, 'Teaching Assistant'),
            (PROFESSOR, 'Professor')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course,                 on_delete=models.CASCADE)
    type = models.IntegerField(choices=TYPE_CHOICES, default=STUDENT)

    def __str__(self):
        return str(self.course) + ' ' + str(self.user) + ': ' + self.get_type_display()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Alma{% block title %}{% endblock %}</title>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/>
	<link type="text/css" rel="stylesheet" href="{% static 'mathquill/mathquill.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'summernote/summernote-lite.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'style.css' %}">
	{% block css_include %}{% endblock %}	
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<style type="text/css">
	{% block style %}{% endblock %}	
	</style>
</head>
<body>

<header>
	<ul id="user-dropdown" class="dropdown-content">
		<li><a href="#"><i class="material-icons left">account_circle</i>Profile</a></li>
		<li><a href="#"><i class="material-icons left">settings</i>Settings</a></li>
		<li><a href="{% url 'logout' %}"><i class="material-icons left">exit_to_app</i>Logout</a></li>
	</ul>
	<ul id="course-select-dropdown" class="dropdown-content">
		{% for course in course_list %}
		<li><a href="{% url 'course_index' course.id %}">{{ course.get_name }}</a></li>
		{% endfor %}
	</ul>
	<div class="navbar-fixed">
		<nav class="white">
			<div class="nav-wrapper">
				<a href="#" data-target="sidenav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
				<a id="logo-large" class="brand-logo left hide-on-med-and-down" href="">Alma</a>
				<a id="logo-small" class="brand-logo left hide-on-large-only" href="">Alma</a>
				<ul class="right">
					<li><a class="dropdown-trigger" href="#!" data-target="course-select-dropdown"><i class="material-icons left">class</i>{{ course.get_name }}<i class="material-icons right">arrow_drop_down</i></a></li>
					<li><a class="dropdown-trigger" href="#!" data-target="user-dropdown"><i class="material-icons hide-on-med-and-up">account_circle</i><span class="hide-on-small-only">{{ user.get_full_name }}</span><i class="material-icons right hide-on-small-only">arrow_drop_down</i></a></li>
				</ul>
			</div>
		</nav>
	</div>
	<ul id="sidenav" class="sidenav sidenav-fixed">
		<li><a href="{% url 'forum:index' course.id %}">Forum</a></li>
		<li><a href="{% url 'assignments:index' course.id %}">Assignments</a></li>
	</ul>
</header>


<a href="#info-modal" id="info-button" data-target="info-modal" class="hide modal-trigger btn-floating btn-large waves-effect waves-light yellow darken-3"><i class="material-icons">info_outline</i></a>
<div id="info-modal" class="modal modal-fixed-footer">
	<div class="modal-content">
	</div>
	<div class="modal-footer"><a class="modal-action modal-close waves-effect waves-green btn-flat" href="#!">Close</a></div>
</div>
<div id="info-tap-target" class="tap-target yellow darken-3" data-target="info-button">
	<div class="tap-target-content">
		<h5>Page Info</h5>
		<p>Click here to get info on this page and a summary of its features.</p>
	</div>
</div>


<main>
{% block main %}{% endblock %}	
</main>

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'mathquill/mathquill.js' %}"></script>
<script type="text/javascript">
var MQ = MathQuill.getInterface(2);
</script>
<script type="text/javascript" src="{% static 'summernote/summernote-lite.js' %}"></script>
<script type="text/javascript" src="{% static 'summernote/plugin/math/summernote-ext-math.js' %}"></script>
<!--<script type="text/javascript" src="{% static 'livereload/run.js' %}"></script>-->
{% block js_include %}{% endblock %}
<script>
$(document).ready(function() {
	$('.sidenav').sidenav();
	$('.dropdown-trigger').dropdown();
	$('.modal').modal();

	$('span.latex').not('.summernote span.latex').each(function() {
		MQ.StaticMath(this);
	});

	if ($('#info-content').length === 1) {
		$('#info-modal > .modal-content').html($('#info-content').html());
		$('#info-button').removeClass('hide');
	}

	{% if info_shown != None %}
	{% if not info_shown %}
	$('#info-tap-target').featureDiscovery();
	$('#info-tap-target').featureDiscovery('open');
	{% endif %}
	{% endif %}



	{% block document_ready %}{% endblock %}
});
</script>
</body>
</html>